'use client';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-4xl font-bold text-text-primary mb-2">Terms of Service</h1>
      <p className="text-text-muted mb-8">Last updated: January 2025</p>

      <div className="space-y-8 text-text-secondary leading-relaxed">
        <section className="bg-bg-card rounded-2xl border border-border-secondary p-8">
          <h2 className="text-xl font-bold text-text-primary mb-4">Acceptance of Terms</h2>
          <p>
            By accessing or using AniBrain, you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use our service.
          </p>
        </section>

        <section className="bg-bg-card rounded-2xl border border-border-secondary p-8">
          <h2 className="text-xl font-bold text-text-primary mb-4">Description of Service</h2>
          <p className="mb-4">
            AniBrain provides AI-powered anime, manga, light novel, and one shot recommendations.
            The service integrates with third-party platforms including AniList and MyAnimeList
            to provide personalized recommendations based on user lists.
          </p>
          <p>
            Recommendations are generated by our AI engine and are provided &ldquo;as is&rdquo;
            without any guarantee of accuracy or personal satisfaction.
          </p>
        </section>

        <section className="bg-bg-card rounded-2xl border border-border-secondary p-8">
          <h2 className="text-xl font-bold text-text-primary mb-4">User Responsibilities</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must provide accurate information when creating an account</li>
            <li>You are responsible for maintaining the confidentiality of your account</li>
            <li>You agree not to misuse the service for any unlawful purpose</li>
            <li>You agree not to attempt to bypass any rate limits or access controls</li>
          </ul>
        </section>

        <section className="bg-bg-card rounded-2xl border border-border-secondary p-8">
          <h2 className="text-xl font-bold text-text-primary mb-4">Intellectual Property</h2>
          <p className="mb-4">
            The AniBrain service, including its AI engine, interface design, and code, is
            proprietary. Anime and manga data, including images and descriptions, are
            sourced from AniList and MyAnimeList and are subject to their respective terms.
          </p>
        </section>

        <section className="bg-bg-card rounded-2xl border border-border-secondary p-8">
          <h2 className="text-xl font-bold text-text-primary mb-4">Limitation of Liability</h2>
          <p>
            AniBrain is provided &ldquo;as is&rdquo; without any warranty. We are not liable
            for any damages arising from the use of our service, including but not limited to
            inaccurate recommendations or service interruptions.
          </p>
        </section>

        <section className="bg-bg-card rounded-2xl border border-border-secondary p-8">
          <h2 className="text-xl font-bold text-text-primary mb-4">Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Users will be notified
            of significant changes via email or through the platform.
          </p>
        </section>
      </div>
    </div>
  );
}
